"""Aggregate per-book _meta.yml files into _data/books.yml.

Reads sibling repos in the workspace root:
- ../nndl/v2/_meta.yml         (理论书 v2)
- ../nndl/ge/_meta.yml         (通识版)
- ../nndl-practice/_meta.yml   (案例与实践)
- ../llm-agent/_meta.yml       (大模型与智能体)

Missing files are skipped with a warning. Output order follows META_PATHS.
"""

from pathlib import Path
import sys

try:
    import yaml
except ImportError:
    sys.exit("Install PyYAML first: pip install pyyaml")

PORTAL = Path(__file__).resolve().parents[1]
ROOT = PORTAL.parent

META_PATHS = [
    ROOT / "nndl"          / "v2" / "_meta.yml",
    ROOT / "nndl-practice" / "_meta.yml",
    ROOT / "nndl"          / "ge" / "_meta.yml",
    ROOT / "llm-agent"     / "_meta.yml",
]

books = []
for p in META_PATHS:
    rel = p.relative_to(ROOT)
    if not p.exists():
        print(f"[skip] {rel} missing")
        continue
    data = yaml.safe_load(p.read_text(encoding="utf-8"))
    books.append(data)
    print(f"[read] {rel} -> key={data.get('key')}")

if not books:
    sys.exit("\nNo _meta.yml files found. Per-book repos not yet populated;\n"
             "_data/books.yml left as-is (hand-maintained initial version).")

out = PORTAL / "_data" / "books.yml"
header = (
    "# Auto-generated by scripts/aggregate-books.py — do not edit by hand.\n"
    "# Source of truth: per-book _meta.yml files in sibling repos.\n\n"
)
out.write_text(
    header + yaml.safe_dump(books, allow_unicode=True, sort_keys=False),
    encoding="utf-8",
)
print(f"\n[ok] wrote {out.relative_to(ROOT)} ({len(books)} books)")
