"""Aggregate per-book _meta.yml files into _data/books.yml.

Reads sibling repos in the workspace root:
- ../nndl/nndl-v2/_meta.yml    (理论书 v2)
- ../nndl/nndl-ge/_meta.yml    (通识版)
- ../nndl-practice/_meta.yml   (案例与实践)
- ../llm-beginner/_meta.yml    (大模型与智能体；元数据随 llm-beginner 仓库维护)

Missing files are skipped with a warning. Output order follows META_PATHS.
"""

from pathlib import Path
import sys

try:
    import yaml
except ImportError:
    sys.exit("Install PyYAML first: pip install pyyaml")

PORTAL = Path(__file__).resolve().parents[1]
ROOT = PORTAL.parent

META_PATHS = [
    ROOT / "nndl"          / "nndl-v2" / "_meta.yml",
    ROOT / "nndl-practice" / "_meta.yml",
    ROOT / "nndl"          / "nndl-ge" / "_meta.yml",
    ROOT / "llm-beginner"  / "_meta.yml",
]

missing = [p for p in META_PATHS if not p.exists()]
if missing:
    sys.exit(
        "Missing _meta.yml files (refusing to write partial books.yml):\n"
        + "\n".join(f"  - {p.relative_to(ROOT)}" for p in missing)
    )

books = []
for p in META_PATHS:
    data = yaml.safe_load(p.read_text(encoding="utf-8"))
    books.append(data)
    print(f"[read] {p.relative_to(ROOT)} -> key={data.get('key')}")

out = PORTAL / "_data" / "books.yml"
header = (
    "# Auto-generated by scripts/aggregate-books.py — do not edit by hand.\n"
    "# Source of truth: per-book _meta.yml files in sibling repos.\n\n"
)
out.write_text(
    header + yaml.safe_dump(books, allow_unicode=True, sort_keys=False),
    encoding="utf-8",
)
print(f"\n[ok] wrote {out.relative_to(ROOT)} ({len(books)} books)")
