"""Fetch GitHub star counts for repos referenced in books.yml.

Writes _data/gh_stars.yml as {slug: count}. Preserves prior values on
fetch error so the site never regresses to an empty badge.

Why this exists: rendering star counts via client-side fetch to
api.github.com fails for visitors whose network or shared NAT IP has
hit the 60 req/hour unauthenticated rate limit (common in China).
Pre-rendering at build time decouples the published page from
api.github.com reachability and rate limits.

Usage::

    python scripts/fetch-gh-stars.py             # unauthenticated, 60/h
    GITHUB_TOKEN=ghp_xxx python scripts/fetch-gh-stars.py   # 5000/h

Run before commit/push when book repos change or you want fresh counts.
"""

from __future__ import annotations

import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("Install PyYAML first: pip install pyyaml")

PORTAL = Path(__file__).resolve().parents[1]
BOOKS_YML = PORTAL / "_data" / "books.yml"
STARS_YML = PORTAL / "_data" / "gh_stars.yml"

# Repos referenced outside books.yml (e.g. site-wide nav badge).
EXTRA_REPOS = ["nndl/nndl"]


def slug_from_url(url: str) -> str | None:
    if not url:
        return None
    s = url.strip()
    for prefix in ("https://github.com/", "http://github.com/"):
        if s.startswith(prefix):
            s = s[len(prefix):]
            break
    else:
        return None
    if s.endswith(".git"):
        s = s[:-4]
    s = s.rstrip("/")
    return s if "/" in s else None


def collect_slugs() -> list[str]:
    books = yaml.safe_load(BOOKS_YML.read_text(encoding="utf-8")) or []
    slugs: set[str] = set(EXTRA_REPOS)
    for b in books:
        s = slug_from_url(b.get("repo", "") or "")
        if s:
            slugs.add(s)
    return sorted(slugs)


def load_existing() -> dict[str, int]:
    if not STARS_YML.exists():
        return {}
    try:
        data = yaml.safe_load(STARS_YML.read_text(encoding="utf-8")) or {}
    except Exception:
        return {}
    return {str(k): int(v) for k, v in data.items() if isinstance(v, (int, float))}


def fetch_stars(slug: str, token: str | None) -> int | None:
    req = urllib.request.Request(f"https://api.github.com/repos/{slug}")
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("User-Agent", "nndl-portal-build")
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            data = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        body = ""
        try:
            body = e.read().decode("utf-8", errors="replace")[:200]
        except Exception:
            pass
        print(f"  ! {slug}: HTTP {e.code} {body}")
        return None
    except Exception as e:
        print(f"  ! {slug}: {e!r}")
        return None
    n = data.get("stargazers_count")
    return int(n) if isinstance(n, (int, float)) else None


def main() -> int:
    slugs = collect_slugs()
    existing = load_existing()
    token = os.environ.get("GITHUB_TOKEN") or None
    if token:
        print(f"[auth] using GITHUB_TOKEN (***{token[-4:]})")
    else:
        print("[auth] unauthenticated (60 req/hour per IP)")

    stars: dict[str, int] = {}
    fresh = 0
    kept = 0
    for slug in slugs:
        n = fetch_stars(slug, token)
        if n is not None:
            stars[slug] = n
            print(f"  ok  {slug}: {n}")
            fresh += 1
        elif slug in existing:
            stars[slug] = existing[slug]
            print(f"  ..  {slug}: keep prior ({existing[slug]})")
            kept += 1
        else:
            print(f"  --  {slug}: no value (badge will show —)")

    STARS_YML.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# Auto-generated by scripts/fetch-gh-stars.py - do not edit by hand.\n"
        "# Map of <owner>/<repo> -> stargazers_count.\n"
        "# Run the script to refresh; prior values are kept when API fails.\n\n"
    )
    STARS_YML.write_text(
        header + yaml.safe_dump(stars, sort_keys=True, allow_unicode=True),
        encoding="utf-8",
    )
    print(
        f"\n[ok] wrote {STARS_YML.relative_to(PORTAL)} "
        f"({fresh} fresh, {kept} kept, {len(slugs) - fresh - kept} missing)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
